name: Build

on: [ push, pull_request ]

permissions:
  contents: write  # 需要写入权限来创建 release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
  release:
    needs: build  # 依赖构建任务完成
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: package
          path: build/libs

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1  # 使用官方推荐的 ncipollo/release-action
        with:
          # 基础配置
          token: ${{ github.token }}  # 自动使用 GitHub 令牌，无需额外配置
          # 版本标签（必填，建议使用语义化版本或动态日期）
          tag: v${{ github.sha == github.head_sha && github.ref_type == 'branch' && format('{0}-{1}', github.ref_name, github.run_number) || github.ref_name }}
          # 版本名称（可选，默认使用标签）
          name: Release ${{ github.ref_name }}
          # 版本描述（支持 Markdown，或通过 bodyFile 指定文件路径）
          body: |
            ### 构建信息
            - 构建时间：${{ github.run_timestamp }}
            - 提交哈希：[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          # 上传产物（支持单个文件或通配符，多个路径用逗号分隔）
          artifacts: build/libs/**/*.jar
          asset_path: build/libs/${{ env.artifact_name }}
          asset_name: ${{ env.artifact_name }}
          asset_content_type: application/java-archive
        env:
          artifact_name: $(ls build/libs)
