name: Build

on: [ push, pull_request ]

permissions:
  contents: write  # 需要写入权限来创建 release
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
  release:
    needs: build  # 依赖 build job 完成
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
          path: build/libs

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.date }}-preview  # 使用日期作为版本号
          release_name: Preview Release ${{ env.date }}
          draft: false
          prerelease: true  # 标记为预发布版本
          body: |
            这是一个自动生成的预览版本。
            包含以下构建产物：
            ${{ steps.list_files.outputs.files }}

      - name: List files for release
        id: list_files
        run: |
          FILES=$(ls build/libs | tr '\n' ' ')
          echo "files=$FILES" >> $GITHUB_ENV
          echo "::set-output name=files::$FILES"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/${{ env.artifact_name }}
          asset_name: ${{ env.artifact_name }}
          asset_content_type: application/java-archive
        env:
          artifact_name: $(ls build/libs)
